baseURL = "https://johnjago.com"
languageCode = "en-us"
title = "johnjago.com"
rssLimit = 25
assetDir = "static"

[params]
	description = "I like to create things and write about what I learn along the way."
	images = ['images/card.png']
	blogHome = "blog/"
	allPostsText = "read more"
	script = '<script src="https://zhidao.johnjago.com/script.js" data-site="MZJJIBDM" defer></script>'

[menu]
	[[menu.main]]
		name = "say hi"
		url = "hi/"
		weight = 1
	[[menu.main]]
		name = "blogroll"
		url = "blogroll/"
		weight = 2
	[[menu.main]]
		name = "projects"
		url = "projects/"
		weight = 3
	[[menu.main]]
		name = "work logs"
		url = "https://undo.studio"
		weight = 4
