baseURL = 'https://johnjago.com'
languageCode = 'en-us'
title = 'John Jago'
rssLimit = 25

[params]
	description = 'My public journal where I share what I’m working on, reading, and thinking about.'
	images = ['card.png']
