baseURL = "https://johnjago.com/blog/"
languageCode = "en-us"
title = "John’s Software Blog"
theme = "journal"

[author]
  name = "John Jago"
  homepage = "https://johnjago.com"

[params]
  description = "Sharing what I learn about software development, languages, and the industry as a whole."
  tagline = "Languages and other musings"

[[menu.main]]
  name = "小笔记"
  url = "https://xiaobiji.co"
[[menu.main]]
  name = "johnjago.com"
  url = "https://johnjago.com"
[[menu.main]]
  name = "About"
  url = "about/"
