baseURL = "https://johnjago.com/blog/"
languageCode = "en-us"
title = "johnjago.com"
theme = "timeless"

[params]
  description = "Thoughts and ideas on software and language."
  footerSymbol = "~"
  allPostsText = "read more"
  serif = true

[menu]
  [[menu.main]]
    name = "say hi"
    url = "about"
    weight = 2
  [[menu.main]]
    name = "projects"
    url = "https://johnjago.com"
    weight = 3
